spring.application.name=gateway-service
server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=account-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://account-service:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/accounts/**

spring.cloud.gateway.server.webmvc.routes[1].id=transaction-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://transaction-service:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/transactions/**

spring.cloud.gateway.server.webmvc.routes[2].id=payment-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://payment-service:8083
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/payments/**

jwt.secret=${JWT_SECRET}
app.auth.username=${AUTH_USERNAME:demo-user}
app.auth.password=${AUTH_PASSWORD:demo-pass}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
